### ISSUE TITLE
N1上运行一段时间后容器会退出

### ISSUE THREAD

**Issue by fanxin11** [jance-hui/update-jd-ck#1]
不知道怎么搜集异常退出的日志，大佬如果有意修复的话可以指导一下吗

**Comment by jance-hui** [comment]
可以`docker logs -f  容器名称` 看一下容器自身的日志。
我之前遇到过spy隔几天经常挂断，还无法自动重启，就写了个定时任务，每天重启容器

**Comment by jance-hui** [comment]
内存问题，docker容器启动时将` -m 256m`去除即可。
docker运行（x86架构）：docker run -d -it -p 9833:9833 --name update-jd-ck jancehui/update-jd-ck:1.1
docker运行（arm架构）：docker run -d -it -p 9833:9833 --name update-jd-ck jancehui/update-jd-ck:arm64-v8-1.1
