### ISSUE TITLE
复制的内容只有 pt_key 时，会默认更新第一个

### ISSUE THREAD

**Issue by winterwd** [jance-hui/update-jd-ck#2]
api接口需要对参数非空处理

稍微改了捷径指令，对参数处理了下
https://www.icloud.com/shortcuts/735411661217465c82eb79eb055d1e37

**Comment by winterwd** [comment]
修改了下捷径，扩展了可通过 共享执行，也对 pt_pin加了判断

https://www.icloud.com/shortcuts/148a4c35416240cea9a2be1837f63381

**Comment by jance-hui** [comment]
此方案针对的是使用alook复制全部ck信息。同时可针对多个pt_pin时，避免其他的被覆盖。
主要是提供一个方便自己更新ck的方式。可以自己个性化调整快捷指令、代码，重新打包
